name: continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
           python-version: "3.10"
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Install dependencies
        run: |
          sudo apt-get upgrade && apt-get update
          sudo apt-get install python3-sphinx
          sudo apt-get install ghp-import
          python -m pip install --upgrade pip
          pip install sphinx_rtd_theme
          pip install imageio
          pip install flake8 pytest pytest-cov

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          cd tests/
          pytest -vv --cov

      - name: Build HTML
        run: |
          cd docs/
          make html

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/_build/html
